export default [
    "Building 1",
    "Building 2",
    "Building 3",
    "Building 4",
    "Building 5",
    "Building 6",
    "Building 7",
    "Building 8",
    "Building 9",
    "Building 10",
    "Building 11",
    "Building 12",
    "Building 13",
    "Building 14",
];
